attrib -R about.dfm
attrib -R about.pas
attrib -R com00.dfm
attrib -R com00.pas
attrib -R comdlg.dfm
attrib -R comdlg.pas
attrib -R ComSb01.dfm
attrib -R ComSb01.pas
attrib -R ComSb02.dfm
attrib -R ComSb02.pas
attrib -R DB_ACC.dfm
attrib -R DB_ACC.pas
attrib -R EPrint.pas
attrib -R ErrorMsg.pas
attrib -R fMsgTyp1.dfm
attrib -R fMsgTyp1.pas
attrib -R fMsgTyp2.dfm
attrib -R fMsgTyp2.pas
attrib -R fMsgTyp3.dfm
attrib -R fMsgTyp3.pas
attrib -R Gval.pas
attrib -R help.pas
attrib -R helpmap.pas
attrib -R myInitInf.pas
attrib -R pdct_com.pas
attrib -R pdct_ini.pas
attrib -R prgMsg.dfm
attrib -R prgMsg.pas
attrib -R print.dfm
attrib -R print.pas
attrib -R PrtCom00.dfm
attrib -R PrtCom00.pas
attrib -R Trace.pas

